#!/bin/ksh
cd ..
MODEL_E_ROOT=$PWD
DECKS_DIR=${MODEL_E_ROOT}/decks
AUX_DIR=${MODEL_E_ROOT}/aux
BIN_DIR=${DECKS_DIR}/$qflux_test3_bin
CMRUNDIR=/u/cmrun
if [[ ! -d ${CMRUNDIR} ]] ; then CMRUNDIR=/giss ; fi
if [[ -f ~/.modelErc ]]; then . ~/.modelErc; fi

runID=qflux_test3
cd $CMRUNDIR/$runID
rm -f RSFIC* OHT OHTnoID

z12o_max=0
while [[ ${z12o_max} != [1-9][0-9][0-9] ]] && [[ ${z12o_max} != [1-9][0-9] ]]
do echo "Enter the maximal mixed layer depth (m) as an integer (11-999)"
   read z12o_max
done

do_uln=1 ; if [[ ! -L TOPO ]] ; then ${runID}ln ; do_uln=0 ; fi

set -A month -- xx JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC
rsfic=1${month[1]}$(( 1950 + 12/12 )).rsf${1} ; qc=$BIN_DIR/${qc} ; sfx=''
if [[ -s ${rsfic}.nc ]] ; then
   qc=$AUX_DIR/qcnc ; sfx='.nc'
fi

echo 'Enter rsf file for new initial conditions'
echo "   (path from `pwd` or absolute pathname):"
echo "   or hit enter if $rsfic$sfx is ok:"
read rsficx
if [[ ${rsficx} != '' ]]
then rsfic=${rsficx} ; sfx=''
  if [[ ${rsfic} = *'.nc' ]]
  then rsfic=${rsfic%.nc} ; sfx='.nc'
  fi
fi

ln -s $rsfic$sfx RSFIC${sfx}
if [[ -s RSFIC${sfx} ]]
then
  if ( ${qc} RSFIC${sfx} ) then
      echo "This RSF file contains part of the I.C. for the new run"
      echo "It will be used to create a new i.c. file by this program"
  else
    echo "Error in $qc program. "
    echo "Ensure that it is up-to-date with a 'gmake aux RUN=${runID}' command from ../decks."
    exit
  fi
else echo "RSF file not found, please start over"
     exit
fi

echo " "
echo "Reading in saved ocean data..."
echo "  ${BIN_DIR}/vertflux.exe qflux_test3 1 1950 12 1950 > vertflux.qflux_test3.1950-1950.PRT "
if ( ! ${BIN_DIR}/vertflux.exe qflux_test3 1 1950 12 1950  > vertflux.qflux_test3.1950-1950.PRT ) then
    echo " "
    echo "  Problem reading in vertical flux data. Aborting."
    exit
fi
echo "Done"
echo " "
  mv SRCOR  SRCOR.line.$1.$3-$5
